import 'dart:ui';
import 'package:flutter/material.dart';
import 'package:myapp/models/color_scheme_model.dart';

class AppThemes {
  static const AppColorScheme light = AppColorScheme(
    primary: Color(0xFF0D47A1),
    background: Color(0xFFF0F5F9),
    secondary: Color(0xFF546E7A),
    tertiary: Color(0xFF90A4AE),
    disabled: Color(0xFFD6E0EA),
    onDisabled: Color(0xFF7A94B5),
    onSurface: Colors.black87,
    surface: Colors.white,
    text: Colors.black87,
    textSelection: Color(0xFFBBDEFB),
    textFaded: Colors.black54,
    textSecondary: Colors.black54,
    overlayBackground: Colors.black54,
    gridBackgroundColor: Color(0xFFF8F7FA),
    border: Color(0xFFE0E0E0),
    borderIntense: Color(0xFFBDBDBD),
    success: Color(0xFF2E7D32),
    danger: Color(0xFFC62828),
    warning: Color(0xFFFFA500),
    successLight: Color(0xFFE8F5E9),
    dangerLight: Color(0xFFFFEBEE),
    dialogShadowColor: Color(0x66000000),
    removeBtnColor: Color(0xFFB26363),
    editBtnColor: Color(0xFFCEA14F),
    neutralLight: Color(0xFFE0E0E0),
    neutralMedium: Color(0xFF757575),
    neutralStrong: Color(0xFF616161),
    menuTileColors: [
      Color(0xFF2F80ED),
      Color(0xFF27AE60),
      Color(0xFFF2994A),
      Color(0xFFEB5757),
      Color(0xFF9B51E0),
      Color(0xFF56CCF2),
    ],
    passwordStrengthBarIndicatorColors: [
      Colors.cyan,
      Colors.blue,
      Colors.purple,
    ],
    cardBackground: Color(0xFFF5F5F5),

  );

  static const AppColorScheme dark = AppColorScheme(
    primary: Color(0xFF90CAF9),
    background: Color(0xFF121212),
    secondary: Color(0xFFB0BEC5),
    tertiary: Color(0xFF78909C),
    disabled: Color(0xFF424242),
    onDisabled: Color(0xFF9E9E9E),
    surface: Colors.black,
    onSurface: Colors.white,
    text: Colors.white,
    textSelection: Color(0xFF546E7A),
    textFaded: Colors.white70,
    textSecondary: Colors.white70,
    overlayBackground: Colors.black54,
    gridBackgroundColor: Color(0xFF1E1E2A),
    border: Color(0xFF424242),
    borderIntense: Color(0xFF616161),
    success: Color(0xFF81C784),
    danger: Color(0xFFE57373),
    warning: Color(0xFFFFB74D),
    successLight: Color(0xFF1B5E20),
    dangerLight: Color(0xFFB71C1C),
    dialogShadowColor: Color(0xCC000000),
    removeBtnColor: Color(0xFFEF9A9A),
    editBtnColor: Color(0xFFFFCC80),
    neutralLight: Color(0xFF424242),
    neutralMedium: Color(0xFF9E9E9E),
    neutralStrong: Color(0xFFBDBDBD),
    menuTileColors: [
      Color(0xFF64B5F6),
      Color(0xFF81C784),
      Color(0xFFFFB74D),
      Color(0xFFE57373),
      Color(0xFFBA68C8),
      Color(0xFF4DD0E1),
    ],
    passwordStrengthBarIndicatorColors: [
      Colors.lightBlueAccent,
      Colors.lightGreenAccent,
      Colors.purpleAccent,
    ],
    cardBackground: Color(0xFF2A2A2A),
  );
}
